type SpellingWordsDict = {
    [year: string]: {
        [group: string]: string[];
    };
};

export const SpellingWords: SpellingWordsDict = {
    'Year 4': {
        'Essential Spelling List 1': [
            'a... A cat sat on the mat... A.',
            'I... I am happy... i',
            'it... it was cool... it',
            'the... The cat sat on the mat... The',
            'was... Was that you?... was',
            'and... And another thing... And',
            'in... In the house... In',
            'my... My brother from another mother... my',
            'to... To be or not to be... To',
            'we... We went to the shops... We',
        ],
        'Essential Spelling List 2': [
            'at... At noon we have lunch... at',
            'had... Had you thought of that?... had',
            'of... The government of New Zealand... of',
            'that... That dog is smelly... that',
            'up... Up and down... up',
            'but... But what about me?... but',
            'he... He is smelly... he',
            'on... On the top of the hill... on',
            'then... Then we will have lunch... then',
            'went... We went to the shops... went',
            'for... What did you do that for?... for',
            'is... Is that all?... is',
            'she... She is smelly... she',
            'there... Over there... there',
            'when... When will we have lunch... when',
            'got... Have you got a minute?... got',
            'me... What about me?... me',
            'so... So what?... so',
            'they... They are smelly... they',
            'you... You are not smelly... you',
        ],
        'Essential Spelling List 3': [
            'about... What about me?... about',
            'after... After lunch we can play... after',
            'all... All your base are belong to us... all',
            'are... Are you sure?... are',
            'as... Simple as pie... as',
            'back... Back to the future... back',
            'be... To be or not to be... be',
            'because... Because I said so... because',
            'came... The cat came back... came',
            'day... What day is it?... day',
            'down... Up and down... down',
            'get... get out of here... get',
            'go... Go to the shops... go',
            "going... Let's get going... going",
            'have... Have you had lunch?... have',
            'her... her dog is smelly... her',
            'his... his dog is smelly... his',
            'home... My home is in New Zealand... home',
            'into... Out of the frying pan, into the fire... into',
            'just... Just do it... just',
            'like... I like ice cream... like',
            'mum... Mum is the word... mum',
            'not... Do not do that... not',
            'one... one is just before two... one',
            'our... Our house in the middle of our street... our',
            'out... Go outside and play... out',
            "said... That's what I said... said",
            "some... Some day, you're going to get caught... some",
            'were... Our people, once were warriors... were',
            'with... Do you want to go to the shops with me?... with',
        ],
        'Essential Spelling List 4': [
            'again... Over and over again... again',
            'an... An apple a day keeps the doctor away... an',
            "around... Let's meet around noon... around",
            'big... New York is also called the Big Apple... big',
            'by... Hamlet is a play by William Shakespeare... by',
            'can... Can you spell can?... can',
            'come... Would you like to come to my party?... come',
            'could... Could you, would you, on a boat?... could',
            'dad... Why did mum come in this list before dad?... dad',
            'did... Did you hear that?... did',
            'do... Do not be silly... do',
            'first... First things first... first',
            'food... Food is what we eat... food',
            'from... From first principles... from',
            'good... The good, the bad, and the ugly... good',
            'has... Has it occurred to you... has',
            "him... Let's get hime... him",
            'house... My house is white... house',
            'if... If only I could spell if... if',
            'little... Little house on the prairie... little',
            'next... Next door lives a dog... next',
            'night... It is dark at night... night',
            'no... No more mister nice guy... no',
            'now... Now I am hungry... now',
            'off... Get off me... off',
            'old... I too old for this... old',
            'only... If only I had more cheese... only',
            'or... This way or that way or?... or',
            "other... Let's go the other way... other",
            'over... Come over here... over',
            "people... People are stupid, lot's of people... people",
            'put... Put up your toys away... put',
            'ran... I ran in the race... ran',
            'saw... I saw you... saw',
            'school... I go to school every day... school',
            'see... See I told you so... see',
            'started... I just started at school... started',
            'their... What is their problem?... their',
            "them... Let's get them... them",
            'this... This is ridiculous... this',
            'time... It is time to party... time',
            'took... I took the ball... took',
            'two... two is between one and three... two',
            'us... Amoung us... us',
            'very... You are very tall... very',
            'well... Well that escalated quickly... well',
            'what... What are you doing?... what',
            'will... Will you sit with me... will',
            'would... Would you like to sit with me... would',
            "your... What's your problem?... your",
        ],
        'Essential Spelling List 5': [
            'am... I am hungry... am',
            'another... brother from another mother... another',
            'away... Home and away... away',
            'bed... Go to bed... bed',
            "been... It's been a hard day... been",
            'before... Have I met you before?... before',
            'best... You are the best... best',
            'brother... brother from another mother... brother',
            'called... Your mother called... called',
            'car... We drove to school in the car... car',
            'door... Shut the door... door',
            'everyone... everyone knows your name... everyone',
            'family... My family like to eat... family',
            'five... I have five fingers... five',
            'found... I found a coin on the beach... found',
            'friend... You are my friend... friend',
            'fun... Did you have fun?... fun',
            'heard... I heard you were looking for me... heard',
            'here... Get over here... here',
            "know... I didn't know that... know",
            'last... The last of us... last',
            'left... Left or right... left',
            'long... So long and thanks for all the fish... long',
            "looked... I looked around and didn't see it... looked",
            'made... A self made man... made',
            'man... A self made man... man',
            'more... Give me more... more',
            'morning... The sun comes up in the morning ... morning',
            'name... What is your name... name',
            'never... Never say never... never',
            'once... Once I met a donkey... once',
            'play... Go play outside... play',
            'really... Do you really mean that?... really',
            'room... What room are you in... room',
            'something... Something is wrong... something',
            'still... Why are you still here?... still',
            'thing... The thing is... thing',
            'think... Think about it... think',
            'thought... I thought I told you... thought',
            'three... Three is between two and four... three',
            "through... Let's go through here... through",
            'told... I told you so... told',
            'too... The soup is too hot... too',
            'walked... I walked out of there... walked',
            'want... I want to go... want',
            'way... You give way at a give way sign... way',
            'where... Where are you going?... where',
            'which... which are you?... which',
            'who... who are you?... who',
            'year... what year is it?... year',
        ],
        'Essential Spelling List 6': [
            'also... I also want to come... also',
            'always... Always get enough sleep... always',
            'asked... I asked around... asked',
            'black... Black or white... black',
            'boy... A boy grows up into a man... boy',
            'bus... We caught the bus to town... bus',
            'cat... The cat sat on the mat... cat',
            'coming... Are you coming to the party?... coming',
            'minutes... How many minutes?... minutes',
            'most... Most cats sit on mats... most',
            'much... How much does it cost... much',
            'nice... No more mister nice guy... nice',
            'opened... I opened the can... opened',
            'outside... Go outside and play... outside',
            'each... Give one to each child... each',
            'cool... It is cool in the winter... cool',
            'dark... It is dark outside at night... dark',
            'decided... Have you decided what to eat for lunch... decided',
            "dog... It's a dog eat dog world... dog",
            "eat... It's a dog eat dog world... eat",
            'end... In the end... end',
            'even... Even steven... even',
            'every... Every dog needs to eat... every',
            'place... Right time right place... place',
            'ready... Get ready for your spelling test... ready',
            'ride... Can your ride a bike?... ride',
            'right... Left or right... right',
            'run... Did you run in the cross country?... run',
            'say... What did you say... say',
            'ground... The ground beneath our feet... ground',
            'eyes... Show me your eyes... eyes',
            'fell... I fell over and got back up... fell',
            'felt... I felt that too... felt',
            'find... Did you find your hat?... find',
            'four... Four is between three and five... four',
            'gave... I gave you your present already... gave',
            "getting... It's getting hot in here... getting",
            'great... Have a great day... great',
            'sister... Do you have a sister?... sister',
            "sleep... It's time to sleep... sleep",
            "suddenly... Suddenly I don't feel so cold... suddenly",
            'take... Take a break... take',
            'tell... Tell me another one... tell',
            'ten... I have ten finger... ten',
            'money... Do you have enough money?... money',
            'head... Get your head screwed on right... head',
            'hit... He hit the ball hard... hit',
            'how... How did you do that?... how',
            'inside... It must be an inside job... inside',
            'its... The dog has a tail; its tail is wagging. The possesive its... its',
            "it's... It's raining outside. The contraction of it is... it's",
            "I'll... I'll put you down. The contraction of I will... I'll",
            'top... We climed to the top of the moutain... top',
            "town... Let's go to town... town",
            'tree... Issac sat under an apple tree reading a boook... tree',
            'turned... We turned around and went the other way... turned',
            'until... Eat until you feel full... until',
            'wanted... I wanted another monkey... wanted',
            'soon... Soon we will have all the monkeys... soon',
            "jump... Let's jump in the water... jump",
            'knew... I knew you could spell knew... knew',
            "later... Let's get ice cream later... later",
            'life... Life is like a box of chocolates... life',
            'live... Live and let live... live',
            'lot... That is a lot to take in... lot',
            'lunch... What are we having for lunch... lunch',
            'make... Kiss and make up... make',
            'water... Water just falls from the sky... water',
            'while... While you were sleeping... while',
            'why... Why did you do that?... why',
            'window... Please close the window... window',
            'woke... I woke up and smelled the coffee... woke',
            'yes... Yes or no... yes',
        ],
        'Essential Spelling List 7': [
            'any... Any reason you think that way?... any',
            'baby... A baby needs a lot of attention... baby',
            'bad... You smell bad... bad',
            'ball... Get the ball rolling... ball',
            'being... Am I being silly?... being',
            'bit... You smell a bit funny... bit',
            'boat... The goat ate oat on the boat... boat',
            'bought... I bought some ice cream at the store... bought',
            "camp... Let's go camp in the woods... camp",
            'dead... The walking dead... dead',
            'died... The dog died of boredom... died',
            'doing... What are you doing?... doing',
            'each... Each to his own... each',
            'ever... Never, not ever... ever',
            'everything... Everything is upside down... everything',
            'face... Your eyes are on your face... face',
            'fast... The fast and furious... fast',
            'father... Father is another word for dad... father',
            'few... Few and far between... few',
            'finally... I finally finished my spelling... finally',
            'finished... I finally finished my spelling... finished',
            "game... Let's play a game... game",
            'girl... A girl is a young woman... girl',
            'gone... He has gone to the store... gone',
            'ground... The ground beneath your feet... ground',
            'guard... Guard up... guard',
            'hand... Give me a hand... hand',
            'happened... What happened... happened',
            "happy... If you're happy and you know it clap your hands... happy",
            'help... Help me... help',
            "hole... There's a hole in my bucket... hole",
            'hot... The soup is too hot... hot',
            'hour... The hour is getting late... hour',
            'let... Let it go... let',
            'look... Look over there, I can see a monkey... look',
            'many... Many monkeys smell very bad... many',
            'money... Many problems can be solved with money... money',
            'mother... Mother is another word for mum... mother',
            'myself... Me, myself, and I... myself',
            'new... I got a new bicycle for my birthday... new',
            'parents... My parents are so cool... parents',
            'picked... I was picked for the team... picked',
            'playing... I have been playing too much screen time... playing',
            'presents... we give presents on birthdays... presents',
            'road... Cars drive on the road... road',
            'side... Whoose side are you on?... side',
            'small... Big or small... small',
            'sometimes... Sometimes I smell bad... sometimes',
            'soon... Soon I will be able to spell soon... soon',
            'stay... Stay away or I will fart... stay',
            'stop... Stop doing that, or I will fart... stop',
            "swimming... Let's go swimming in the water... swimming",
            'tea... My parents drink green tea... tea',
            "than... I'd rather eat ice cream than brocolli... than",
            'tried... I am tired,... tried',
            'under... Under the bridge lives a troll... under',
            'wait... Wait a minute... wait',
            'won... I won the game, I am the winner... won',
            'work... All work and no play, makes Jack a dull boy... work',
            'world... Hello world... world',
        ],
        'Essential Spelling List 8': [
            "allowed... You're not allowed to be in here... allowed",
            "doesn't... Doesn't that bother you?... doesn't",
            'hospital... Sick people go to hospital... hospital',
            'threw... He threw the ball... threw',
            'cannon... Cannons fire cannon balls... cannon',
            'everywhere... Everything everywhere all at once... everywhere',
            'police... The police stop bad people from being bad... police',
            "weren't... Weren't you at the shops?... weren't",
            'clothes... You wear clothes on your body... clothes',
            'front... The front is not at the back... front',
            'second... Second is right after first... second',
            'disappeared... The money disappeared from the table, did you steal it?... disappeared',
            'hopped... I had hoped you would learn your spelling... hopped',
            "they're... They're very smelly. Short for they are very smelly... they're",
            'brought... I brought my favourite monkey along... brought',
            'everyday... Everyday I go to school... everyday',
            'nearly... It is nearly time for lunch... nearly',
            'watch... I like to watch video... watch',
            'chocolate... I like to each chocolate... chocolate',
            'friends... Can we be friends... friends',
            "scared... Don't be scared... scared",
            'someone... Someone smells funny... someone',
            'holidays... In the holidays we go travelling... holidays',
            'straight... Straight up and down... straight',
            'breakfast... I eat breakfast in the morning... breakfast',
            'everybody... Everybody smells funny... everybody',
            'luckily... Luckily I smell good... luckily',
            "wasn't... Wasn't there a bar here?... wasn't",
            'centre... The centre is in the middle... centre',
            'field... Wheat grows in the field... field',
            'quiet... All was quiet as a mouse... quiet',
            'grabbed... I grabbed an apple and ate it... grabbed',
            'different... Something is different about you... different',
            'stopped... I stopped smelling when I had a shower... stopped',
            "believe... I don't believe you... believe",
            'tomorrow... Tomorrow I will have a shower... tomorrow',
            'lightning... Thunder and lightning... lightning',
            'video... My phone can record video... video',
            "caught... You've been caught red handed... caught",
            'favourite... My favourite ice cream is vanilla... favourite',
            'probably... You probably smell bad... probably',
            'whole... I ate a whole pizza, all of it, every slice... whole',
            "won't... won't you take a shower?... won't",
            'having... I am having a good day... having',
            'awhile... stay awhile so we can talk... awhile',
            "dollars... He's got more dollars than sense... dollars",
            'instead... Instead of playing games do some spelling... instead',
            "don't... Don't talk that way to me... don't",
            "can't... Don't say you can't do it, say you can't do it yet... can't",
            "excited... Don't get excited... excited",
            'present... I would like to give you a present... present',
            "we're... we're going out, short for we are going out... we're",
            "couldn't... Couldn't you take a shower... couldn't",
            "didn't... Didn't you take a shower... didn't",
            "you're... You're smelly. Short for you are smelly... you're",
        ],
    },
    'Year 8': {
        'List 1': [
            'abundance... Out of an abundance of caution... abundance',
            'accommodate... I cannot accommodate your bad body odor... accommodate',
            'acknowledge... I acknowledge your efforts... acknowledge',
            'acquire... How did you acquire that big gun?... acquire',
            'aggravate... Do not aggravate me... aggravate',
            'appropriate... Your behavior was appropriate... appropriate',
            'assassin... Someone kill that assassin before he kills me... assassin',
            'ballerina... A ballet dancer is called a ballerina... ballerina',
            'bachelor... An unmarried man is called a bachelor... bachelor',
            'banquet... A large meal is called a banquet... banquet',
        ],
        'List 2': [
            'because... Because I said so... because',
            'brutality... Brutality means to do something very violently... brutality',
            'building... We are building a new world... building',
            'business... Mind your own business... business',
            'category... We group thinngs into categories... category',
            'conscious... I made a conscious decision to improve my spelling... conscious',
            'constellation... A constellation is a group of stars... constellation',
            'correspondence... Correspondence is another word for written communication... correspondence',
            'colleagues... I work alongside my colleagues... colleagues',
            'commemorate... We commemorate the efforts of people who helped others... commemorate',
        ],
        'List 3': [
            'commission... To commission means to order and pay for something to be created... commission',
            'committee... A committee is a group which decides on something together... committee',
            'compatible... Something is compatible if they can fit together... compatible',
            'comparative... Comparative means to compare... comparative',
            'competent... You are a competent speller... competent',
            'connoisseur... A connoisseur is someone who is an expert in a thing... connoisseur',
            'contribute... You should contribute to society... contribute',
            'copious... Copious means a large amount, like a copious amount of beer... copious',
            'corroborate... I was able to corroborate his story... corroborate',
            'courteous... Be courteous to people you meet... courteous',
        ],
        'List 4': [
            'criticism... Criticism can help you improve... criticism',
            'deceitful... Deceitful people should be avoided... deceitful',
            'diary... I write daily in my diary... diary',
            'disappoint... Sorry to disappoint you... disappoint',
            'desperate... Best to not appear desperate... desperate',
            'deterrent... I carry big muscles as a deterrent... deterrent',
            'disastrous... This situation is disastrous... disastrous',
            'dissatisfied... I am dissatisfied with the price of fish... dissatisfied',
            'donkey... Would you like to ride on my donkey... donkey',
        ],
        'List 5': [
            'earnest... To be earnest means to be keen and engaged... earnest',
            'efficient... Being efficient means to eliminate wasted effort... efficient',
            'endurance... To run for long periods requires strong endurance... endurance',
            'embarrass... Do not embarrass yourself... embarrass',
            'equipped... You will be well equipped to pass your spelling test... equipped',
            'essential... Good spelling is essential... essential',
            "especially... I am especially happy you're working on your spelling... especially",
            'exception... The exception that proves the rule... exception',
            'fascinate... Bad smells fascinate me... fascinate',
            'feasible... That seems feasible... feasible',
        ],
        'List 6': [
            'February... February is the second month of the year... February',
            'foreign... foreign means unknown to you, like from a foreign country... foreign',
            "friends... Let's be friends forever... friends",
            'government... The government rules by consent in democratic countries... government',
            'grievance... A grievance is a real or imagined complaint... grievance',
            'gauge... A gauge measures something, like a water pressure gauge... gauge',
            'guile... He used his guile and smarts to free himself... guile',
            'guardian... A guardian protects... guardian',
            'height... Your height is measured in centimetres... height',
            'honorary... An honorary member of a group... honorary',
            'hypocrisy... Hypocrisy is the practice of claiming to have higher moral standards than demonstrated... hypocrisy',
        ],
        'List 7': [
            "illiterate... Illiterate people can't read... illiterate",
            'illuminate... Light can illuminate the darkness... illuminate',
            'immigrant... An immigrant comes to our country to live... immigrant',
            'incidentally... Incidentally I also realized... incidentally',
            'indespensable... Being able to spell is indespensable to good writing... indespensable',
            "irrelevant... Don't include irrelevant points in your writing... irrelevant",
            'irreparable... Things which are irreparable cannot be repaired... irreparable',
            'irresistable... I find chocolate irresistable... irresistable',
            'immediately... Your spelling will improve immediately if your practice... immediately',
            'independent... An independent adult can survive on their own... independent',
        ],
        'List 8': [
            'liasion... A liasion acts as a go between two groups or people... liasion',
            'manipulation... Manipulation is the art of getting people to give you what you want... manipulation',
            'manoeuvre... Armies manoeuvre on the battlefield... manoeuvre',
            'maintenance... Houses require maintenance... maintenance',
            "medicine... Medicine helps us recover when we're sick... medicine",
            'Mediterranean... The Mediterranean sea lies between Europe and Africa... Mediterranean',
            'microphone... A microphone records sound... microphone',
            'miniature... Miniature things are smaller than the real thing... miniature',
            'minutes... How many minutes in an hour?... minutes',
            'mortgage... The money you borrow to buy a house is called a mortgage... mortgage',
        ],
        'List 9': [
            'moveable... Is this object moveable?... moveable',
            'monetary... The government sets monetary policy to control the economy... monetary',
            'muscular... Most muscular discomfort can be helped with massage... muscular',
            'negotiable... All things are negotiable... negotiable',
            "necessary... It's not possible, it's necessary... necessary",
            'notorious... Someone notorious is well know for being bad... notorious',
            'nostalgia... Nostalgia is a wistful affection for the past... nostalgia',
        ],
        'List 10': [
            'occasion... You will rise to the occasion... occasion',
            'occasional... Occasional things happen infrequently... occasional',
            'occurrence... The occurrence of something is how often it occurs... occurrence',
            'parallel... Parallel lines lie side by side and never touch... parallel',
            'paralleled... paralleled things are made to be paralle... paralleled',
            'parliament... The New Zealand parliament sits in Wellington... parliament',
            'perspective... Your perspective is your point of view... perspective',
            'pedestrain... A pedestrain walks beside the road... pedestrain',
            'penicillin... Penicillin was the first antibiotic discovered... penicillin',
            'pharmacy... You get medicines from a pharmacy... pharmacy',
        ],
        'List 11': [
            'prestige... Prestige is widespread respect... prestige',
            'prevention... Prevention stops something from happening... prevention',
            "procrastinate... Don't procrastinate, get on with it... procrastinate",
            'recognition... Most people want recognition of their efforts and skills... recognition',
            'seize... My army will seize your position... seize',
            'science... Science is the systematic study of the universe by experimentation and observation... science',
            'scissors... Rock, paper, scissors... scissors',
            'separate... To pull apart is to separate... separate',
            'symphony... The symphony orchestra sounds nice... symphony',
            'synonym... A synonym is a word that means the same as another... synonym',
        ],
        'List 12': [
            'tangible... Something tangible can be touched... tangible',
            'technician... A technician is trained to operate something technical... technician',
            'thoughtless... Thoughtless words can hurt... thoughtless',
            'unconscious... Knocked unconscious... unconscious',
            'unparalleled... His stupidity was unparalleled... unparalleled',
            'usually... I usually shower in the evening... usually',
            "vague... That's a vague and unclear statement... vague",
            'valuable... Being able to spell is a valuable skill... valuable',
            'vulnerable... To be vulnerable means to be in a position of weakness... vulnerable',
            'view... The view from here is spectacular... view',
            'Wednesday... The day after Tuesday... Wednesday',
            'whimsical... Playfully quant or fanciful... whimsical',
        ],
    },
};
